# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../views/templates/ext_info_win_dark.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_extended_info_form(object):
    def setupUi(self, extended_info_form):
        extended_info_form.setObjectName("extended_info_form")
        extended_info_form.resize(1589, 963)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(extended_info_form.sizePolicy().hasHeightForWidth())
        extended_info_form.setSizePolicy(sizePolicy)
        extended_info_form.setStyleSheet("QWidget {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.label = QtWidgets.QLabel(extended_info_form)
        self.label.setGeometry(QtCore.QRect(10, 10, 1561, 941))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/images/about_program.png"))
        self.label.setScaledContents(True)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")

        self.retranslateUi(extended_info_form)
        QtCore.QMetaObject.connectSlotsByName(extended_info_form)

    def retranslateUi(self, extended_info_form):
        _translate = QtCore.QCoreApplication.translate
        extended_info_form.setWindowTitle(_translate("extended_info_form", "Расширенная информация о программе"))
from resources import extended_info_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    extended_info_form = QtWidgets.QWidget()
    ui = Ui_extended_info_form()
    ui.setupUi(extended_info_form)
    extended_info_form.show()
    sys.exit(app.exec_())
