# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../views/templates/settings_win_dark.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings_form(object):
    def setupUi(self, settings_form):
        settings_form.setObjectName("settings_form")
        settings_form.resize(1060, 780)
        settings_form.setStyleSheet("QWidget {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(settings_form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.section_frame = QtWidgets.QFrame(settings_form)
        self.section_frame.setMinimumSize(QtCore.QSize(300, 0))
        self.section_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.section_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.section_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.section_frame.setObjectName("section_frame")
        self.btn_program_info = QtWidgets.QPushButton(self.section_frame)
        self.btn_program_info.setGeometry(QtCore.QRect(0, 0, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_program_info.setFont(font)
        self.btn_program_info.setStyleSheet("QPushButton {\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(240, 243, 249);\n"
"    border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.btn_program_info.setObjectName("btn_program_info")
        self.btn_color_style = QtWidgets.QPushButton(self.section_frame)
        self.btn_color_style.setGeometry(QtCore.QRect(0, 40, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_color_style.setFont(font)
        self.btn_color_style.setStyleSheet("QPushButton {\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(240, 243, 249);\n"
"    border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.btn_color_style.setObjectName("btn_color_style")
        self.btn_privacy_policy = QtWidgets.QPushButton(self.section_frame)
        self.btn_privacy_policy.setGeometry(QtCore.QRect(0, 280, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_privacy_policy.setFont(font)
        self.btn_privacy_policy.setStyleSheet("QPushButton {\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(240, 243, 249);\n"
"    border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.btn_privacy_policy.setObjectName("btn_privacy_policy")
        self.btn_app_set = QtWidgets.QPushButton(self.section_frame)
        self.btn_app_set.setGeometry(QtCore.QRect(0, 80, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_app_set.setFont(font)
        self.btn_app_set.setStyleSheet("QPushButton {\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(240, 243, 249);\n"
"    border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.btn_app_set.setObjectName("btn_app_set")
        self.btn_quick_panel = QtWidgets.QPushButton(self.section_frame)
        self.btn_quick_panel.setGeometry(QtCore.QRect(0, 160, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_quick_panel.setFont(font)
        self.btn_quick_panel.setStyleSheet("QPushButton {\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(240, 243, 249);\n"
"    border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.btn_quick_panel.setObjectName("btn_quick_panel")
        self.btn_help_set = QtWidgets.QPushButton(self.section_frame)
        self.btn_help_set.setGeometry(QtCore.QRect(0, 240, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_help_set.setFont(font)
        self.btn_help_set.setStyleSheet("QPushButton {\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(240, 243, 249);\n"
"    border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.btn_help_set.setObjectName("btn_help_set")
        self.btn_tab = QtWidgets.QPushButton(self.section_frame)
        self.btn_tab.setGeometry(QtCore.QRect(0, 200, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_tab.setFont(font)
        self.btn_tab.setStyleSheet("QPushButton {\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(240, 243, 249);\n"
"    border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.btn_tab.setObjectName("btn_tab")
        self.btn_line_menu = QtWidgets.QPushButton(self.section_frame)
        self.btn_line_menu.setGeometry(QtCore.QRect(0, 120, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_line_menu.setFont(font)
        self.btn_line_menu.setStyleSheet("QPushButton {\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(240, 243, 249);\n"
"    border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.btn_line_menu.setObjectName("btn_line_menu")
        self.horizontalLayout.addWidget(self.section_frame)
        self.section_widget = QtWidgets.QStackedWidget(settings_form)
        self.section_widget.setObjectName("section_widget")
        self.program_info_page = QtWidgets.QWidget()
        self.program_info_page.setObjectName("program_info_page")
        self.version_lbl = QtWidgets.QLabel(self.program_info_page)
        self.version_lbl.setGeometry(QtCore.QRect(6, 300, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.version_lbl.setFont(font)
        self.version_lbl.setStyleSheet("QLabel {\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.version_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.version_lbl.setWordWrap(True)
        self.version_lbl.setObjectName("version_lbl")
        self.label_3 = QtWidgets.QLabel(self.program_info_page)
        self.label_3.setGeometry(QtCore.QRect(6, 340, 751, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.program_info_page)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(0, 10, 751, 211))
        self.plainTextEdit_2.setStyleSheet("QPlainTextEdit {\n"
"    border: none;\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.ext_info_btn = QtWidgets.QPushButton(self.program_info_page)
        self.ext_info_btn.setGeometry(QtCore.QRect(6, 240, 321, 45))
        self.ext_info_btn.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.ext_info_btn.setObjectName("ext_info_btn")
        self.section_widget.addWidget(self.program_info_page)
        self.color_style_page = QtWidgets.QWidget()
        self.color_style_page.setObjectName("color_style_page")
        self.frame = QtWidgets.QFrame(self.color_style_page)
        self.frame.setGeometry(QtCore.QRect(20, 190, 321, 201))
        self.frame.setStyleSheet("QFrame {\n"
"    border-radius: 5px;\n"
"    background-color: rgb(240, 243, 249);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(180, 160, 120, 30))
        self.frame_2.setStyleSheet("QFrame {\n"
"    border-radius: 3px;\n"
"    background-color: rgb(98, 79, 130);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(180, 120, 120, 30))
        self.frame_3.setStyleSheet("QFrame {\n"
"    border-radius: 3px;\n"
"    background-color: rgb(159, 115, 171);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: rgb(48, 47, 47);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.light_btn = QtWidgets.QPushButton(self.color_style_page)
        self.light_btn.setGeometry(QtCore.QRect(90, 410, 180, 45))
        self.light_btn.setMinimumSize(QtCore.QSize(130, 45))
        self.light_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.light_btn.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.light_btn.setObjectName("light_btn")
        self.dark_btn = QtWidgets.QPushButton(self.color_style_page)
        self.dark_btn.setGeometry(QtCore.QRect(480, 410, 180, 45))
        self.dark_btn.setMinimumSize(QtCore.QSize(130, 45))
        self.dark_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.dark_btn.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.dark_btn.setObjectName("dark_btn")
        self.frame_11 = QtWidgets.QFrame(self.color_style_page)
        self.frame_11.setGeometry(QtCore.QRect(410, 190, 321, 201))
        self.frame_11.setStyleSheet("QFrame {\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(180, 160, 120, 30))
        self.frame_12.setStyleSheet("QFrame {\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"    background-color: rgb(48, 47, 47);\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setGeometry(QtCore.QRect(180, 120, 120, 30))
        self.frame_13.setStyleSheet("QFrame {\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_9 = QtWidgets.QLabel(self.frame_11)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.win_btn = QtWidgets.QPushButton(self.color_style_page)
        self.win_btn.setGeometry(QtCore.QRect(90, 720, 180, 45))
        self.win_btn.setMinimumSize(QtCore.QSize(130, 45))
        self.win_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.win_btn.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.win_btn.setObjectName("win_btn")
        self.frame_4 = QtWidgets.QFrame(self.color_style_page)
        self.frame_4.setGeometry(QtCore.QRect(20, 490, 321, 201))
        self.frame_4.setStyleSheet("QFrame {\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    background-color: rgb(240, 243, 249);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.accent_light_win_color = QtWidgets.QFrame(self.frame_4)
        self.accent_light_win_color.setGeometry(QtCore.QRect(20, 160, 120, 30))
        self.accent_light_win_color.setStyleSheet("QFrame {\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"    background-color: rgb(98, 79, 130);\n"
"}")
        self.accent_light_win_color.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accent_light_win_color.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accent_light_win_color.setObjectName("accent_light_win_color")
        self.compl_light_win_color = QtWidgets.QFrame(self.frame_4)
        self.compl_light_win_color.setGeometry(QtCore.QRect(20, 120, 120, 30))
        self.compl_light_win_color.setStyleSheet("QFrame {\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"    background-color: rgb(159, 115, 171);\n"
"}")
        self.compl_light_win_color.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.compl_light_win_color.setFrameShadow(QtWidgets.QFrame.Raised)
        self.compl_light_win_color.setObjectName("compl_light_win_color")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    color: rgb(48, 47, 47);\n"
"}")
        self.label_8.setObjectName("label_8")
        self.frame_17 = QtWidgets.QFrame(self.frame_4)
        self.frame_17.setGeometry(QtCore.QRect(160, 0, 161, 201))
        self.frame_17.setStyleSheet("QFrame {\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    border-bottom-left-radius: 0;\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_11 = QtWidgets.QLabel(self.frame_17)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.compl_dark_win_color = QtWidgets.QFrame(self.frame_17)
        self.compl_dark_win_color.setGeometry(QtCore.QRect(20, 120, 120, 30))
        self.compl_dark_win_color.setStyleSheet("QFrame {\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.compl_dark_win_color.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.compl_dark_win_color.setFrameShadow(QtWidgets.QFrame.Raised)
        self.compl_dark_win_color.setObjectName("compl_dark_win_color")
        self.accent_dark_win_color = QtWidgets.QFrame(self.frame_17)
        self.accent_dark_win_color.setGeometry(QtCore.QRect(20, 160, 120, 30))
        self.accent_dark_win_color.setStyleSheet("QFrame {\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"    background-color: rgb(48, 47, 47);\n"
"}")
        self.accent_dark_win_color.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accent_dark_win_color.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accent_dark_win_color.setObjectName("accent_dark_win_color")
        self.time_color_btn = QtWidgets.QPushButton(self.color_style_page)
        self.time_color_btn.setGeometry(QtCore.QRect(480, 720, 180, 45))
        self.time_color_btn.setMinimumSize(QtCore.QSize(130, 45))
        self.time_color_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.time_color_btn.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.time_color_btn.setObjectName("time_color_btn")
        self.frame_14 = QtWidgets.QFrame(self.color_style_page)
        self.frame_14.setGeometry(QtCore.QRect(410, 490, 321, 201))
        self.frame_14.setStyleSheet("QFrame {\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    background-color: rgb(240, 243, 249);\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setGeometry(QtCore.QRect(20, 160, 120, 30))
        self.frame_15.setStyleSheet("QFrame {\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"    background-color: rgb(98, 79, 130);\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setGeometry(QtCore.QRect(20, 120, 120, 30))
        self.frame_16.setStyleSheet("QFrame {\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"    background-color: rgb(159, 115, 171);\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_10 = QtWidgets.QLabel(self.frame_14)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    color: rgb(48, 47, 47);\n"
"}")
        self.label_10.setObjectName("label_10")
        self.frame_20 = QtWidgets.QFrame(self.frame_14)
        self.frame_20.setGeometry(QtCore.QRect(160, 0, 161, 201))
        self.frame_20.setStyleSheet("QFrame {\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    border-bottom-left-radius: 0;\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.label_12 = QtWidgets.QLabel(self.frame_20)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setGeometry(QtCore.QRect(20, 120, 120, 30))
        self.frame_21.setStyleSheet("QFrame {\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setGeometry(QtCore.QRect(20, 160, 120, 30))
        self.frame_22.setStyleSheet("QFrame {\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"    background-color: rgb(48, 47, 47);\n"
"}")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.color_style_page)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 10, 751, 131))
        self.plainTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    border: none;\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.dark_style_frame = QtWidgets.QFrame(self.color_style_page)
        self.dark_style_frame.setGeometry(QtCore.QRect(400, 180, 343, 222))
        self.dark_style_frame.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgba(240, 243, 249, 150);\n"
"}")
        self.dark_style_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dark_style_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dark_style_frame.setObjectName("dark_style_frame")
        self.system_style_frame = QtWidgets.QFrame(self.color_style_page)
        self.system_style_frame.setGeometry(QtCore.QRect(10, 480, 343, 222))
        self.system_style_frame.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgba(240, 243, 249, 150);\n"
"}")
        self.system_style_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.system_style_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.system_style_frame.setObjectName("system_style_frame")
        self.time_color_style_frame = QtWidgets.QFrame(self.color_style_page)
        self.time_color_style_frame.setGeometry(QtCore.QRect(400, 480, 343, 222))
        self.time_color_style_frame.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgba(240, 243, 249, 150);\n"
"}")
        self.time_color_style_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.time_color_style_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.time_color_style_frame.setObjectName("time_color_style_frame")
        self.light_style_frame = QtWidgets.QFrame(self.color_style_page)
        self.light_style_frame.setGeometry(QtCore.QRect(10, 180, 343, 222))
        self.light_style_frame.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgba(240, 243, 249, 150);\n"
"}")
        self.light_style_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.light_style_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.light_style_frame.setObjectName("light_style_frame")
        self.light_style_frame.raise_()
        self.time_color_style_frame.raise_()
        self.system_style_frame.raise_()
        self.dark_style_frame.raise_()
        self.frame.raise_()
        self.light_btn.raise_()
        self.dark_btn.raise_()
        self.frame_11.raise_()
        self.win_btn.raise_()
        self.frame_4.raise_()
        self.time_color_btn.raise_()
        self.frame_14.raise_()
        self.plainTextEdit.raise_()
        self.section_widget.addWidget(self.color_style_page)
        self.app_set_page = QtWidgets.QWidget()
        self.app_set_page.setObjectName("app_set_page")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.app_set_page)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(0, 10, 751, 91))
        self.plainTextEdit_4.setStyleSheet("QPlainTextEdit {\n"
"    border: none;\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.plainTextEdit_4.setReadOnly(True)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.label_4 = QtWidgets.QLabel(self.app_set_page)
        self.label_4.setGeometry(QtCore.QRect(6, 120, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.confirm_quit_chk = QtWidgets.QCheckBox(self.app_set_page)
        self.confirm_quit_chk.setGeometry(QtCore.QRect(630, 108, 101, 45))
        self.confirm_quit_chk.setMinimumSize(QtCore.QSize(0, 45))
        self.confirm_quit_chk.setStyleSheet("QCheckBox {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius: 2px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border-radius: 2px;\n"
"    background-color: rgb(67, 67, 67);\n"
"}")
        self.confirm_quit_chk.setText("")
        self.confirm_quit_chk.setObjectName("confirm_quit_chk")
        self.btn_restart = QtWidgets.QPushButton(self.app_set_page)
        self.btn_restart.setGeometry(QtCore.QRect(6, 170, 180, 45))
        self.btn_restart.setMinimumSize(QtCore.QSize(130, 45))
        self.btn_restart.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_restart.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.btn_restart.setObjectName("btn_restart")
        self.btn_quit = QtWidgets.QPushButton(self.app_set_page)
        self.btn_quit.setGeometry(QtCore.QRect(200, 170, 180, 45))
        self.btn_quit.setMinimumSize(QtCore.QSize(130, 45))
        self.btn_quit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_quit.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.btn_quit.setObjectName("btn_quit")
        self.section_widget.addWidget(self.app_set_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(self.page)
        self.plainTextEdit_8.setGeometry(QtCore.QRect(0, 10, 751, 91))
        self.plainTextEdit_8.setStyleSheet("QPlainTextEdit {\n"
"    border: none;\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.plainTextEdit_8.setReadOnly(True)
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(6, 120, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.menu_line_chk = QtWidgets.QCheckBox(self.page)
        self.menu_line_chk.setGeometry(QtCore.QRect(220, 108, 171, 45))
        self.menu_line_chk.setMinimumSize(QtCore.QSize(0, 45))
        self.menu_line_chk.setStyleSheet("QCheckBox {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius: 2px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border-radius: 2px;\n"
"    background-color: rgb(67, 67, 67);\n"
"}")
        self.menu_line_chk.setText("")
        self.menu_line_chk.setObjectName("menu_line_chk")
        self.section_widget.addWidget(self.page)
        self.qiuck_panel_page = QtWidgets.QWidget()
        self.qiuck_panel_page.setObjectName("qiuck_panel_page")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.qiuck_panel_page)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(0, 10, 751, 91))
        self.plainTextEdit_5.setStyleSheet("QPlainTextEdit {\n"
"    border: none;\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.plainTextEdit_5.setReadOnly(True)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.label_5 = QtWidgets.QLabel(self.qiuck_panel_page)
        self.label_5.setGeometry(QtCore.QRect(6, 120, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.quick_panel_chk = QtWidgets.QCheckBox(self.qiuck_panel_page)
        self.quick_panel_chk.setGeometry(QtCore.QRect(310, 108, 101, 45))
        self.quick_panel_chk.setMinimumSize(QtCore.QSize(0, 45))
        self.quick_panel_chk.setStyleSheet("QCheckBox {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius: 2px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border-radius: 2px;\n"
"    background-color: rgb(67, 67, 67);\n"
"}")
        self.quick_panel_chk.setText("")
        self.quick_panel_chk.setObjectName("quick_panel_chk")
        self.section_widget.addWidget(self.qiuck_panel_page)
        self.tab_page = QtWidgets.QWidget()
        self.tab_page.setObjectName("tab_page")
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.tab_page)
        self.plainTextEdit_7.setGeometry(QtCore.QRect(0, 10, 751, 91))
        self.plainTextEdit_7.setStyleSheet("QPlainTextEdit {\n"
"    border: none;\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.plainTextEdit_7.setReadOnly(True)
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.frame_18 = QtWidgets.QFrame(self.tab_page)
        self.frame_18.setGeometry(QtCore.QRect(16, 130, 321, 201))
        self.frame_18.setStyleSheet("QFrame {\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.tab_corner_frame = QtWidgets.QFrame(self.tab_page)
        self.tab_corner_frame.setGeometry(QtCore.QRect(6, 120, 343, 222))
        self.tab_corner_frame.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgba(240, 243, 249, 150);\n"
"}")
        self.tab_corner_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tab_corner_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tab_corner_frame.setObjectName("tab_corner_frame")
        self.tab_corner_wgt = QtWidgets.QTabWidget(self.tab_page)
        self.tab_corner_wgt.setGeometry(QtCore.QRect(20, 140, 311, 181))
        self.tab_corner_wgt.setStyleSheet("QTabWidget::pane {\n"
"    background: rgb(46, 44, 44);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    height: 20px;\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    padding: 10 40px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border: 1px solid rgb(30, 30, 30);\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.tab_corner_wgt.setObjectName("tab_corner_wgt")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tab_corner_wgt.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab_corner_wgt.addTab(self.tab_2, "")
        self.tab_radius_frame = QtWidgets.QFrame(self.tab_page)
        self.tab_radius_frame.setGeometry(QtCore.QRect(400, 120, 343, 222))
        self.tab_radius_frame.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgba(240, 243, 249, 150);\n"
"}")
        self.tab_radius_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tab_radius_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tab_radius_frame.setObjectName("tab_radius_frame")
        self.tab_radius_wgt = QtWidgets.QTabWidget(self.tab_page)
        self.tab_radius_wgt.setGeometry(QtCore.QRect(414, 140, 311, 181))
        self.tab_radius_wgt.setStyleSheet("QTabWidget::pane {\n"
"    background: rgb(46, 44, 44);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    height: 20px;\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-radius: 3px;\n"
"    padding: 10 40px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border: 1px solid rgb(30, 30, 30);\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.tab_radius_wgt.setObjectName("tab_radius_wgt")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tab_radius_wgt.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tab_radius_wgt.addTab(self.tab_4, "")
        self.frame_19 = QtWidgets.QFrame(self.tab_page)
        self.frame_19.setGeometry(QtCore.QRect(410, 130, 321, 201))
        self.frame_19.setStyleSheet("QFrame {\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.tab_corner_btn = QtWidgets.QPushButton(self.tab_page)
        self.tab_corner_btn.setGeometry(QtCore.QRect(90, 360, 180, 45))
        self.tab_corner_btn.setMinimumSize(QtCore.QSize(130, 45))
        self.tab_corner_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tab_corner_btn.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.tab_corner_btn.setObjectName("tab_corner_btn")
        self.tab_radius_btn = QtWidgets.QPushButton(self.tab_page)
        self.tab_radius_btn.setGeometry(QtCore.QRect(480, 360, 180, 45))
        self.tab_radius_btn.setMinimumSize(QtCore.QSize(130, 45))
        self.tab_radius_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tab_radius_btn.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.tab_radius_btn.setObjectName("tab_radius_btn")
        self.tab_top_radius_btn = QtWidgets.QPushButton(self.tab_page)
        self.tab_top_radius_btn.setGeometry(QtCore.QRect(94, 670, 180, 45))
        self.tab_top_radius_btn.setMinimumSize(QtCore.QSize(130, 45))
        self.tab_top_radius_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tab_top_radius_btn.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.tab_top_radius_btn.setObjectName("tab_top_radius_btn")
        self.tab_top_radius_frame = QtWidgets.QFrame(self.tab_page)
        self.tab_top_radius_frame.setGeometry(QtCore.QRect(10, 430, 343, 222))
        self.tab_top_radius_frame.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgba(240, 243, 249, 150);\n"
"}")
        self.tab_top_radius_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tab_top_radius_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tab_top_radius_frame.setObjectName("tab_top_radius_frame")
        self.tab_top_radius_wgt = QtWidgets.QTabWidget(self.tab_page)
        self.tab_top_radius_wgt.setGeometry(QtCore.QRect(24, 450, 311, 181))
        self.tab_top_radius_wgt.setStyleSheet("QTabWidget::pane {\n"
"    background: rgb(46, 44, 44);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    height: 20px;\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    padding: 10 40px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border: 1px solid rgb(30, 30, 30);\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.tab_top_radius_wgt.setObjectName("tab_top_radius_wgt")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tab_top_radius_wgt.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tab_top_radius_wgt.addTab(self.tab_10, "")
        self.frame_35 = QtWidgets.QFrame(self.tab_page)
        self.frame_35.setGeometry(QtCore.QRect(20, 440, 321, 201))
        self.frame_35.setStyleSheet("QFrame {\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.tab_corner_radius_btn = QtWidgets.QPushButton(self.tab_page)
        self.tab_corner_radius_btn.setGeometry(QtCore.QRect(484, 670, 180, 45))
        self.tab_corner_radius_btn.setMinimumSize(QtCore.QSize(130, 45))
        self.tab_corner_radius_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tab_corner_radius_btn.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.tab_corner_radius_btn.setObjectName("tab_corner_radius_btn")
        self.tab_corner_radius_wgt = QtWidgets.QTabWidget(self.tab_page)
        self.tab_corner_radius_wgt.setGeometry(QtCore.QRect(414, 450, 311, 181))
        self.tab_corner_radius_wgt.setStyleSheet("QTabWidget::pane {\n"
"    background: rgb(46, 44, 44);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    height: 20px;\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-top-right-radius: 6px;\n"
"    padding: 10 40px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border: 1px solid rgb(30, 30, 30);\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.tab_corner_radius_wgt.setObjectName("tab_corner_radius_wgt")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tab_corner_radius_wgt.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tab_corner_radius_wgt.addTab(self.tab_12, "")
        self.tab_corner_radius_frame = QtWidgets.QFrame(self.tab_page)
        self.tab_corner_radius_frame.setGeometry(QtCore.QRect(400, 430, 343, 222))
        self.tab_corner_radius_frame.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgba(240, 243, 249, 150);\n"
"}")
        self.tab_corner_radius_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tab_corner_radius_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tab_corner_radius_frame.setObjectName("tab_corner_radius_frame")
        self.frame_36 = QtWidgets.QFrame(self.tab_page)
        self.frame_36.setGeometry(QtCore.QRect(410, 440, 321, 201))
        self.frame_36.setStyleSheet("QFrame {\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.tab_corner_radius_frame.raise_()
        self.frame_36.raise_()
        self.tab_top_radius_frame.raise_()
        self.frame_35.raise_()
        self.tab_radius_frame.raise_()
        self.frame_19.raise_()
        self.tab_corner_frame.raise_()
        self.plainTextEdit_7.raise_()
        self.frame_18.raise_()
        self.tab_corner_wgt.raise_()
        self.tab_radius_wgt.raise_()
        self.tab_corner_btn.raise_()
        self.tab_radius_btn.raise_()
        self.tab_top_radius_btn.raise_()
        self.tab_top_radius_wgt.raise_()
        self.tab_corner_radius_btn.raise_()
        self.tab_corner_radius_wgt.raise_()
        self.section_widget.addWidget(self.tab_page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.page_4)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(0, 10, 751, 91))
        self.plainTextEdit_6.setStyleSheet("QPlainTextEdit {\n"
"    border: none;\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.plainTextEdit_6.setReadOnly(True)
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.help_open_btn = QtWidgets.QPushButton(self.page_4)
        self.help_open_btn.setGeometry(QtCore.QRect(6, 120, 211, 45))
        self.help_open_btn.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(77, 77, 77);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(48, 47, 47);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        self.help_open_btn.setObjectName("help_open_btn")
        self.section_widget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.page_3)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(3, 13, 751, 441))
        self.plainTextEdit_3.setStyleSheet("QPlainTextEdit {\n"
"    border: none;\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.section_widget.addWidget(self.page_3)
        self.horizontalLayout.addWidget(self.section_widget)

        self.retranslateUi(settings_form)
        self.section_widget.setCurrentIndex(0)
        self.tab_corner_wgt.setCurrentIndex(0)
        self.tab_radius_wgt.setCurrentIndex(0)
        self.tab_top_radius_wgt.setCurrentIndex(0)
        self.tab_corner_radius_wgt.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settings_form)

    def retranslateUi(self, settings_form):
        _translate = QtCore.QCoreApplication.translate
        settings_form.setWindowTitle(_translate("settings_form", "Настройки"))
        self.btn_program_info.setText(_translate("settings_form", "О приложении"))
        self.btn_color_style.setText(_translate("settings_form", "Цветовая схема"))
        self.btn_privacy_policy.setText(_translate("settings_form", "Политика конфиденциальности"))
        self.btn_app_set.setText(_translate("settings_form", "Рабочая область"))
        self.btn_quick_panel.setText(_translate("settings_form", "Панель быстрого доступа"))
        self.btn_help_set.setText(_translate("settings_form", "Справка"))
        self.btn_tab.setText(_translate("settings_form", "Вкладки"))
        self.btn_line_menu.setText(_translate("settings_form", "Строка меню"))
        self.version_lbl.setText(_translate("settings_form", "Версия: MCrypt 1.9.1 Preview"))
        self.label_3.setText(_translate("settings_form", "©MCryptTeam, 2023, все права защищены"))
        self.plainTextEdit_2.setPlainText(_translate("settings_form", "MCrypt - программное обеспечение, позволяющее выполнять шифрование, дешифрование, хеширование и множество других преобразований быстро и эффективно. При этом, MCrypt позволяет просмотреть каждый шаг выполнения данных преобразований, а также содержит справочник по различным алгоритмам шифрования, применяемых в данном программном обеспечении, что позволяет более подробно рассмотреть различные процессы преобразования данных. Также MCrypt содержит множество различных алгоритмов шифрования, включая более сложные алгоритмы шифрования, предоставляя возможность автоматического заполнения параметров шифрования, что позволяет существенно сократить время на шифрование данных"))
        self.ext_info_btn.setText(_translate("settings_form", "Открыть расширенную информацию"))
        self.label_6.setText(_translate("settings_form", "☀"))
        self.light_btn.setText(_translate("settings_form", "Применить"))
        self.dark_btn.setText(_translate("settings_form", "Применить"))
        self.label_9.setText(_translate("settings_form", "🌙"))
        self.win_btn.setText(_translate("settings_form", "Применить"))
        self.label_8.setText(_translate("settings_form", "☀"))
        self.label_11.setText(_translate("settings_form", "🌙"))
        self.time_color_btn.setText(_translate("settings_form", "Применить"))
        self.label_10.setText(_translate("settings_form", "☀"))
        self.label_12.setText(_translate("settings_form", "🌙"))
        self.plainTextEdit.setPlainText(_translate("settings_form", "Цветовая схема позволяет настроить цветовое оформление элементов интерфейса приложения. Вы можете настроить отображение светлого или темного оформления, а также системного оформления. Системное оформление позволяет отображать цвета элементов в зависимости от выбранных в персонализации Windows цветов. Также вы можете выбрать автоматический режим смены цветового оформления в зависимости от текущего времени суток\n"
"ВАЖНО: Изменения этого параметра вступают в силу после перезагрузки приложения!"))
        self.plainTextEdit_4.setPlainText(_translate("settings_form", "Этот раздел содержит возможности, связанные с основной рабочей областью приложения. Вы можете выполнить завершение работы или перезагрузку приложения, а также отключить или включить отображение окна с подтверждением выхода из рабочей области\n"
"ВАЖНО: Изменения этого параметра вступают в силу после перезагрузки приложения!"))
        self.label_4.setText(_translate("settings_form", "Отображать окно подтверждения при завершении или перезагрузке приложения:"))
        self.btn_restart.setText(_translate("settings_form", "Перезагрузить"))
        self.btn_quit.setText(_translate("settings_form", "Завершить работу"))
        self.plainTextEdit_8.setPlainText(_translate("settings_form", "Строка меню содержит навигацию по основным возможностям приложения. Вы можете отключить или включить отображение строки меню, а также выбрать стиль отображения меню приложения\n"
"ВАЖНО: Изменения этого параметра вступают в силу после перезагрузки приложения!"))
        self.label_7.setText(_translate("settings_form", "Отображать строку меню:"))
        self.plainTextEdit_5.setPlainText(_translate("settings_form", "Панель быстрого доступа позволяет быстро перемещаться между некоторыми страницами приложения. Вы можете отключить или включить отображение данной панели\n"
"ВАЖНО: Изменения этого параметра вступают в силу после перезагрузки приложения!"))
        self.label_5.setText(_translate("settings_form", "Отображать панель быстрого доступа:"))
        self.plainTextEdit_7.setPlainText(_translate("settings_form", "Вкладки рабочей области позволяют быстро перемещаться между различными режимами преобразования данных. Вы можете настроить различный стиль отображения данных вкладок\n"
"ВАЖНО: Изменения данного параметра вступают в силу после перезагрузки приложения!"))
        self.tab_corner_wgt.setTabText(self.tab_corner_wgt.indexOf(self.tab), _translate("settings_form", "Вкладка 1"))
        self.tab_corner_wgt.setTabText(self.tab_corner_wgt.indexOf(self.tab_2), _translate("settings_form", "Вкладка 2"))
        self.tab_radius_wgt.setTabText(self.tab_radius_wgt.indexOf(self.tab_3), _translate("settings_form", "Вкладка 1"))
        self.tab_radius_wgt.setTabText(self.tab_radius_wgt.indexOf(self.tab_4), _translate("settings_form", "Вкладка 2"))
        self.tab_corner_btn.setText(_translate("settings_form", "Применить"))
        self.tab_radius_btn.setText(_translate("settings_form", "Применить"))
        self.tab_top_radius_btn.setText(_translate("settings_form", "Применить"))
        self.tab_top_radius_wgt.setTabText(self.tab_top_radius_wgt.indexOf(self.tab_9), _translate("settings_form", "Вкладка 1"))
        self.tab_top_radius_wgt.setTabText(self.tab_top_radius_wgt.indexOf(self.tab_10), _translate("settings_form", "Вкладка 2"))
        self.tab_corner_radius_btn.setText(_translate("settings_form", "Применить"))
        self.tab_corner_radius_wgt.setTabText(self.tab_corner_radius_wgt.indexOf(self.tab_11), _translate("settings_form", "Вкладка 1"))
        self.tab_corner_radius_wgt.setTabText(self.tab_corner_radius_wgt.indexOf(self.tab_12), _translate("settings_form", "Вкладка 2"))
        self.plainTextEdit_6.setPlainText(_translate("settings_form", "Этот раздел содержит сведения о возможностях и навигации в приложении"))
        self.help_open_btn.setText(_translate("settings_form", "Открыть справку"))
        self.plainTextEdit_3.setPlainText(_translate("settings_form", "MCrypt - программное обеспечение, позволяющее выполнять различные преобразования данных в целях обеспечения безопасности и конфиденциальности данных, а также для безопасного способа их передачи и обмена. Данное программное обеспечение не хранит исходную информацию, предназначенную для ее передачи и обмена, поэтому после завершения работы приложения данная информация будет утеряна без возможности восстановления. В MCrypt пользовательские учетные данные хранятся в формате, не позволяющем получить к ним какой-либо доступ. Однако в случае утери каких-либо данных, MCryptTeam не несет никакой ответственности за утерю или получение доступа сторонних лиц к вашим данным.\n"
"ВАЖНО: Данное программное обеспечение предназначено для изучения различных методов шифрования и хеширования данных. Несмотря на то, что в MCrypt есть возможность шифровать и хешировать информацию, данные возможности, как правило, предназначены также для дополнительного и более подробного изучения. В MCrypt различные алгоритмы обладают достаточной степенью надежности, чтобы защитить ваши данные, однако мы настоятельно не рекомендуем использовать данное программное обеспечение, если вам действительно необходимо обеспечить реальную защиту данных!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settings_form = QtWidgets.QWidget()
    ui = Ui_settings_form()
    ui.setupUi(settings_form)
    settings_form.show()
    sys.exit(app.exec_())
