# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../src/views/templates/account_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_account_form(object):
    def setupUi(self, account_form):
        account_form.setObjectName("account_form")
        account_form.resize(934, 631)
        account_form.setStyleSheet("QWidget {\n"
"    background-color: rgb(240, 243, 249);\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(account_form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.account_wgt = QtWidgets.QStackedWidget(account_form)
        self.account_wgt.setObjectName("account_wgt")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_3 = QtWidgets.QLabel(self.page_5)
        self.label_3.setGeometry(QtCore.QRect(305, 110, 311, 21))
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.registration_username_txt = QtWidgets.QLineEdit(self.page_5)
        self.registration_username_txt.setGeometry(QtCore.QRect(255, 180, 391, 45))
        self.registration_username_txt.setMinimumSize(QtCore.QSize(0, 45))
        self.registration_username_txt.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(98, 79, 130);\n"
"    border-radius: 3px;\n"
"    margin: 0 0 0 18px;\n"
"    padding: 0 3px;\n"
"    color: rgb(48, 47, 47);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(98, 79, 130);\n"
"    background-color: rgb(98, 79, 130);\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.registration_username_txt.setClearButtonEnabled(True)
        self.registration_username_txt.setObjectName("registration_username_txt")
        self.registration_password_txt = QtWidgets.QLineEdit(self.page_5)
        self.registration_password_txt.setGeometry(QtCore.QRect(255, 250, 391, 45))
        self.registration_password_txt.setMinimumSize(QtCore.QSize(0, 45))
        self.registration_password_txt.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(98, 79, 130);\n"
"    border-radius: 3px;\n"
"    margin: 0 0 0 18px;\n"
"    padding: 0 3px;\n"
"    color: rgb(48, 47, 47);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(98, 79, 130);\n"
"    background-color: rgb(98, 79, 130);\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.registration_password_txt.setClearButtonEnabled(True)
        self.registration_password_txt.setObjectName("registration_password_txt")
        self.registration_confirm_password_txt = QtWidgets.QLineEdit(self.page_5)
        self.registration_confirm_password_txt.setGeometry(QtCore.QRect(255, 320, 391, 45))
        self.registration_confirm_password_txt.setMinimumSize(QtCore.QSize(0, 45))
        self.registration_confirm_password_txt.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(98, 79, 130);\n"
"    border-radius: 3px;\n"
"    margin: 0 0 0 18px;\n"
"    padding: 0 3px;\n"
"    color: rgb(48, 47, 47);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(98, 79, 130);\n"
"    background-color: rgb(98, 79, 130);\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.registration_confirm_password_txt.setClearButtonEnabled(True)
        self.registration_confirm_password_txt.setObjectName("registration_confirm_password_txt")
        self.btn_registration = QtWidgets.QPushButton(self.page_5)
        self.btn_registration.setGeometry(QtCore.QRect(380, 400, 161, 45))
        self.btn_registration.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(98, 79, 130);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(98, 79, 130);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid rgb(159, 115, 171);\n"
"    background-color: rgb(159, 115, 171);\n"
"}")
        self.btn_registration.setObjectName("btn_registration")
        self.btn_login_page = QtWidgets.QPushButton(self.page_5)
        self.btn_login_page.setGeometry(QtCore.QRect(273, 470, 371, 31))
        self.btn_login_page.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(98, 79, 130, 50);\n"
"}")
        self.btn_login_page.setObjectName("btn_login_page")
        self.account_wgt.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_4 = QtWidgets.QLabel(self.page_6)
        self.label_4.setGeometry(QtCore.QRect(305, 110, 311, 21))
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.btn_login = QtWidgets.QPushButton(self.page_6)
        self.btn_login.setGeometry(QtCore.QRect(380, 330, 161, 45))
        self.btn_login.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(98, 79, 130);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(98, 79, 130);\n"
"    color: rgb(240, 243, 249);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid rgb(159, 115, 171);\n"
"    background-color: rgb(159, 115, 171);\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.btn_registration_page = QtWidgets.QPushButton(self.page_6)
        self.btn_registration_page.setGeometry(QtCore.QRect(273, 400, 371, 31))
        self.btn_registration_page.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(98, 79, 130, 50);\n"
"}")
        self.btn_registration_page.setObjectName("btn_registration_page")
        self.login_username_txt = QtWidgets.QLineEdit(self.page_6)
        self.login_username_txt.setGeometry(QtCore.QRect(255, 180, 391, 45))
        self.login_username_txt.setMinimumSize(QtCore.QSize(0, 45))
        self.login_username_txt.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(98, 79, 130);\n"
"    border-radius: 3px;\n"
"    margin: 0 0 0 18px;\n"
"    padding: 0 3px;\n"
"    color: rgb(48, 47, 47);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(98, 79, 130);\n"
"    background-color: rgb(98, 79, 130);\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.login_username_txt.setClearButtonEnabled(True)
        self.login_username_txt.setObjectName("login_username_txt")
        self.login_password_txt = QtWidgets.QLineEdit(self.page_6)
        self.login_password_txt.setGeometry(QtCore.QRect(255, 250, 391, 45))
        self.login_password_txt.setMinimumSize(QtCore.QSize(0, 45))
        self.login_password_txt.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(98, 79, 130);\n"
"    border-radius: 3px;\n"
"    margin: 0 0 0 18px;\n"
"    padding: 0 3px;\n"
"    color: rgb(48, 47, 47);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(98, 79, 130);\n"
"    background-color: rgb(98, 79, 130);\n"
"    color: rgb(240, 243, 249);\n"
"}")
        self.login_password_txt.setClearButtonEnabled(True)
        self.login_password_txt.setObjectName("login_password_txt")
        self.account_wgt.addWidget(self.page_6)
        self.horizontalLayout.addWidget(self.account_wgt)

        self.retranslateUi(account_form)
        self.account_wgt.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(account_form)

    def retranslateUi(self, account_form):
        _translate = QtCore.QCoreApplication.translate
        account_form.setWindowTitle(_translate("account_form", "MCrypt"))
        self.label_3.setText(_translate("account_form", "Создайте новую учетную запись MCrypt!"))
        self.registration_username_txt.setPlaceholderText(_translate("account_form", "Имя пользователя"))
        self.registration_password_txt.setPlaceholderText(_translate("account_form", "Пароль"))
        self.registration_confirm_password_txt.setPlaceholderText(_translate("account_form", "Подтвердите пароль"))
        self.btn_registration.setText(_translate("account_form", "Создать"))
        self.btn_login_page.setText(_translate("account_form", "Уже есть учетная запись MCrypt? Войдите в нее!"))
        self.label_4.setText(_translate("account_form", "Войдите в учетную запись MCrypt!"))
        self.btn_login.setText(_translate("account_form", "Войти"))
        self.btn_registration_page.setText(_translate("account_form", "Еще нет учетной записи MCrypt? Создайте ее!"))
        self.login_username_txt.setPlaceholderText(_translate("account_form", "Имя пользователя"))
        self.login_password_txt.setPlaceholderText(_translate("account_form", "Пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    account_form = QtWidgets.QWidget()
    ui = Ui_account_form()
    ui.setupUi(account_form)
    account_form.show()
    sys.exit(app.exec_())
