# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../View/DesignUI/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(649, 463)
        main_window.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 649, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        main_window.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(main_window)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(main_window)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MCrypt"))
        self.menu.setTitle(_translate("main_window", "Файл"))
        self.action.setText(_translate("main_window", "О программе"))
        self.action_2.setText(_translate("main_window", "Справка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
