# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../View/DesignUI/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(649, 463)
        main_window.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.central_widget.setObjectName("central_widget")
        main_window.setCentralWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(main_window)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 649, 18))
        self.menu_bar.setObjectName("menu_bar")
        self.file_menu = QtWidgets.QMenu(self.menu_bar)
        self.file_menu.setObjectName("file_menu")
        main_window.setMenuBar(self.menu_bar)
        self.action_program_info = QtWidgets.QAction(main_window)
        self.action_program_info.setObjectName("action_program_info")
        self.action_help = QtWidgets.QAction(main_window)
        self.action_help.setObjectName("action_help")
        self.file_menu.addAction(self.action_program_info)
        self.file_menu.addAction(self.action_help)
        self.menu_bar.addAction(self.file_menu.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MCrypt"))
        self.file_menu.setTitle(_translate("main_window", "Файл"))
        self.action_program_info.setText(_translate("main_window", "О программе"))
        self.action_help.setText(_translate("main_window", "Справка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
